### PR TITLE
Update composer.json requirements Guzzle

### PR DESCRIPTION
**Pull request by Leandro996**
There isn't Breaking changes with this requirements update. See more info here: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

### CODE REVIEW

**Comment by io238** [comment]
@pfrenssen Can this be merged, please? Thanks.

**Comment by pfrenssen** [comment]
Test report shows that this breaks on older PHP versions. Possibly `~6 || ~7` would be a good idea? Then sites on newer PHP versions can use Guzzle 7, while legacy projects can stay on Guzzle 6.

Let's also extend the `.travis.yml` test matrix to include PHP 7.3 and 7.4.

**Comment by io238** [comment]
Good point. In that case I'd also add PHP 8.0 (latest version) to the `.travis.yml`. Want me to make a PR?

**Comment by pfrenssen** [comment]
Sure go ahead if you have the time, that would be very much appreciated. If it would fail on PHP8, then feel free to leave it out for now.

**Pull request closed without merging**
